title: MUHAMMAD AFIF
description: MAHASISWA SISTEM INFORMASI UIN SUSKA RIAU PEKANBARU
show_downloads: true

baseurl: "/muhammadafif.github.io/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://muhammadafif.github.io" # change this to the base hostname & protocol for your site

cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Lore Pirri"
image: /thumbnail-jumbo.png
twitter:
  username: afhief08
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:
